import { Kanit } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";

const kanit = Kanit({
  subsets: ["thai", "latin"],
  weight: ["400", "600"],
  variable: "--font-kanit",
});

export const metadata = {
  title: "Calctech Camp 2025",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: any) {
  return (
    <html lang="en">
      <body className={`${kanit.variable}`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
